### ISSUE TITLE
Buffered messages remain unsent if an ssl error occures during sending of persistent messages at connect

### ISSUE THREAD

**Issue by mecraggs** [eclipse/paho.mqtt.c#1203]
**Describe the bug**
When a client, with persisted messages, encounters 'SSLSocket error WANT_READ/WANT_WRITE' during connect, all remaining persisted messages at this point will never be sent, MQTTAsync_getPendingTokens will show the exact number of remaining messages. These messages remain unsent until a complete restart/reconnect?. 
Also message ids that are used by persisted messages are skipped, as they never appear in trace messages such as 
```
PUBLISH msgid: 96 ...
PUBLISH msgid: 98 ...
```

**To Reproduce**
* Have ~500+ persisted messages on disk
* Connect via TLS 
* Encounter SSLSocket error WANT_READ/WANT_WRITE' 

**Expected behavior**
All remaining messages should be sent, at  least at some point, as they are present as pending tokens. 

**Log files**
[mqtt-tls-trace.txt](https://github.com/eclipse/paho.mqtt.c/files/8125266/mqtt-tls-trace.txt)

**Environment (please complete the following information):**
 - OS: Linux ( arm64 ) 
 - Version 1.3.9

**Comment by icraggs** [comment]
Hi.  The log only shows what is happening up to the completion of the connection, which is the good part - as in that is working as expected.  The interesting part would be what happens subsequently when MQTTProtocol_retries is called.  

If you have 500 messages persisted, I'm thinking that the majority will be buffered in the command queue and not inflight (the first publish sent), but I see you have a payload of 462 bytes, so that may not be the case. 

I presume you are continuing to send messages after reconnecting, at the rate you were using before (how fast?).   Are you continuing to send messages while the application is disconnected (sendWhileDisconnected)?

**Comment by mecraggs** [comment]
Hi, thanks for your reply. 
Yes, sendWhileDisconnected is enabled. 

We solved this by setting a retryInterval value, [ref](https://github.com/eclipse/paho.mqtt.golang/issues/421) .

**Comment by icraggs** [comment]
Ah, thanks for letting me know.  I think you shouldn't have had to do that in this case.

**Comment by icraggs** [comment]
I've put a fix into the develop branch which should allow this to work without setting the retry interval. I haven't tried it yet, but if you would like to then that would be useful.  Thanks.
