### ISSUE TITLE
Question about Socket_abortWrite which cause memory leak when reconnect internal

### ISSUE THREAD

**Issue by dionysus1016** [eclipse/paho.mqtt.c#1206]
**Describe the bug**
Valgrind complains memory leaks allocated from "ptr = iovec.iov_base = (char *)malloc(iovec.iov_len);"  in SSLSocket_putdatas function, we followed the thread https://github.com/eclipse/paho.mqtt.c/issues/37 and we figure out this issue only happens when the network is very slow and MQTT try to reconnect inside, when our publish call failed, we will destroy the socket but see memory leak there.  After reading codes, the potential root cause might be from the function Socket_abortWrite which skips freeing memory indirectly referenced by pw when SSL is enabled.:

#if defined(OPENSSL)
	if (pw->ssl)
		goto exit;
#endif  

But, as you see, it seems this logic is added for purpose, to fast catchup, could someone tell us why we need to skip to free pw when OpenSSL is enabled?

We are running in Linux.

**Comment by icraggs** [comment]
The skip is there because the processing is different.  See the difference between Socket_continueWrite and SSLSocket_continueWrite.  

Having said that there does look to be some cleanup missing.  SSLSocket_continueWrite cleans things up here:

	if ((rc = SSL_write(pw->ssl, pw->iovecs[0].iov_base, pw->iovecs[0].iov_len)) == pw->iovecs[0].iov_len)
	{
		/* topic and payload buffers are freed elsewhere, when all references to them have been removed */
		free(pw->iovecs[0].iov_base);
		Log(TRACE_MIN, -1, "SSL continueWrite: partial write now complete for socket %d", pw->socket);
		rc = 1;
	}

so it looks like we need to do the same thing:

    #if defined(OPENSSL)
    if (pw->ssl)
    {
         free(pw->iovecs[0].iov_base);
         goto exit;
    }
    #endif

I haven't tried it yet, but if you want to, let me know how it goes.

**Comment by dionysus1016** [comment]
yep, we are testing the code, so far so good. But it looks like a very common code path, wonder why there is no issue for others. We will test the code change for another day, stay tuned.

**Comment by icraggs** [comment]
It might not be very common because you have to:

1. Be using SSL (common)
2. Having large enough payloads or throughput to have an SSL write be unable to completely be written to the socket (not uncommon)
3. Disconnect the client while the write is still in progress (not very common)

Most people probably wouldn't have a network that is "very slow".  Even if they did, then they would probably avoid reconnecting at that point and wait for the publish to complete.  Maybe your keepalive interval should be set larger to cope with the situation of the network being that slow.  It should be bigger at least than the longest time it takes for the publish packet to be written to the socket.

**Comment by icraggs** [comment]
I've added a fix to the develop branch.

**Comment by dionysus1016** [comment]
>

**Comment by dionysus1016** [comment]
Thanks for the comments, for our case, The MQTT client runs in a car that could have poor network condition due to the nature of the cellular network. The device has some throttling issues that firing a new connection is an fast way for recovery (It's true that we lack knowledge of how MQTT reconnect inside...)
