### ISSUE TITLE
Keep Alive is not sent properly

### ISSUE THREAD

**Issue by laszlogyimothy** [eclipse/paho.mqtt.c#1284]
The current implementation of the keep alive handling doesn't work properly. Sending packages to the Client in a loop, blocks sending of keep alive messages => Client will be diconnected by the Broker.

https://github.com/eclipse/paho.mqtt.c/blob/7c0735a5f02052c275baddb4f01f1f4dabdfed20/src/MQTTProtocolClient.c#L731

Correct would be:

>  else if (MQTTTime_difftime(now, client->net.lastSent) >= (DIFF_TIME_TYPE)(client->keepAliveInterval * 1000) **||**
                    MQTTTime_difftime(now, client->net.lastReceived) >= (DIFF_TIME_TYPE)(client->keepAliveInterval * 1000))

or just

>   else if (MQTTTime_difftime(now, client->net.lastSent) >= (DIFF_TIME_TYPE)(client->keepAliveInterval * 1000))

.

See the MQTT specification:

[https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901045](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.oasis-open.org%2Fmqtt%2Fmqtt%2Fv5.0%2Fos%2Fmqtt-v5.0-os.html%23_Toc3901045&data=05%7C01%7Claszlo.gyimothy%40siemens.com%7Caddb635da2974d7a28c808dab9e9e53c%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C638026711464081169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xPDzAGOSnOPHI%2Fgzb1aTW8bJ8%2BREEnPrAk8FFd553Qc%3D&reserved=0)

"The Keep Alive is a Two Byte Integer which is a time interval measured in seconds. It is the maximum time interval that is permitted to elapse between the point at which the Client finishes transmitting one MQTT Control Packet and the point it starts sending the next. It is the responsibility of the Client to ensure that the interval between MQTT Control Packets being sent does not exceed the Keep Alive value. If Keep Alive is non-zero and in the absence of sending any other MQTT Control Packets, the Client MUST send a PINGREQ packet [MQTT-3.1.2-20]."

**Comment by MichaelSchillerIFF** [comment]
I have the same problem. The behaviour was changed in version 1.3.11.

9957c32 -> Free allocated protos field if necessary from14.07.2022

My test was done with the broker from mosquitto v2.0.15.
I only received messages.

**Comment by icraggs** [comment]
I think the commit that changed it is: https://github.com/eclipse/paho.mqtt.c/commit/04656737539b8a82ab19debe4a5e72c40483e033

The second clause:

MQTTTime_difftime(now, client->net.lastReceived) >= (DIFF_TIME_TYPE)(client->keepAliveInterval * 1000)

handles the case when the application is only sending QoS 0 publishes, and there are no packets coming back from the broker. We can't tell then whether the packets are being sent into a black hole.

The and obviously doesn't work for the normal case. I'm going to think about how it interacts with the large packet cases I was thinking about with this commit.

**Comment by icraggs** [comment]
Duplicate of #1277 

I've added a fix to the develop branch if you would like to try it sometime.

**Comment by laszlogyimothy** [comment]
Thank you very much! I will test it!

Ian Craggs ***@***.***> ezt írta (időpont: 2022. nov. 27., V,
17:43):

**Comment by cuttlfish** [comment]
It seems on startup client->net.lastPing is not initialized to anything so it is not tracked until net.lastReceived exceeds the keep-alive time and then it gets reset to current time

**Comment by laszlogyimothy** [comment]
Hi Ian,

I just tested the new release: 1.3.12 and I have faced an issue:


MQTT_Client -> connection_lost callback:

I do a reconnect, I call the MQTTClient_connect5() then I
call MQTTClient_subscribeMany5() and return... => exception here:

[image: image.png]


Based on the documentation, it is allowed to do a reconnect and with the
previous versions it worked as well.
https://eclipse.github.io/paho.mqtt.c/MQTTClient/html/callbacks.html


I just did a comparison between the latest and the previous versions and
this timeout here is new. Probably my action takes more than this timeout
here:

[image: image.png]


Can you please check this issue?

Thank you!

Laszlo


Ian Craggs ***@***.***> ezt írta (időpont: 2022. dec. 21.,
Sze, 12:35):

**Comment by woodz-** [comment]
Even in 3.1.12 the issue persists. Using synchronous variant with QOS 0, if the client doesn't publish continuously, it gets disconnected by the broker and there are no PINGREQ packets sent in between through the client.

So this issue shall be reopened. Thx

**Comment by sergioaiello** [comment]
I have the same problem, and it is a big issue for me since I have no workarounds in my pocket. Is there any?
I have several wireshark traces where the mosquitto broker (2.0.15) node (OPiPC2 / Armbian version=23.02.2) sends a TCP packet FIN and the Paho client (1.3.12) node (OPiZERO / Armbian version=23.02.2) sends a FIN ACK. The network is a LAN (not WLAN) very steady and reliable.
Additional info, maybe not relevant: other clients sends packets to the hub (where the 2 nodes here above operates) and Mosquitto more likely closes the TCP connection as the remote clients increases the traffic. The peripheric nodes do establish dedicated TCP connections and release them as needed on demand.
Please, help since my applications, on MQTT client / local node, have to be always connected to the broker.
Added on Sunday the 7th - Delaying the DISCONNECT from peripheric nodes decreases the chances Mosquitto sends MQTT messages after by. I cannot imagine why this mimic causes Mosquitto to close TCP connection towards the hub MQTT client as well. The hub MQTT client is still not able to re-establish the TCP connection and the problem still remains, but with much lower probability. Of course, I'm still able to re-create the issue if needed.

**Comment by icraggs** [comment]
@sergioaiello you should open another issue and add a client library trace at the protocol level if possible - it seems your issue is different. You should also check the Mosquitto log to see if has any explanation for disconnecting the client. If one of your clients is unable to re-establish a TCP connection, perhaps there is a network or broker problem (is the broker CPU bound for instance).
