### ISSUE TITLE
What is PAHO_USE_SELECT ? 

### ISSUE THREAD

**Issue by Pascal-Fremaux** [eclipse/paho.mqtt.c#1295]
Hello,
The new cmake option PAHO_USE_SELECT is unclear to be an improvement or a regression and it is not documented.

Could you elaborate ?

**Comment by fpagliughi** [comment]
In v1.3.10 the library was updated to use the `poll()` system call to await incoming network packets instead of the older `select()` . This should have better performance and scalability. For most users, it's an invisible update, but if you need to support an old system that doesn't have `poll()`, or if there are any other issues with the new implementation, you can revert back to the older behavior by setting `PAHO_USE_SELECT`.

**Comment by Pascal-Fremaux** [comment]
OK thank you.
