### ISSUE TITLE
the callback writecontinue is null

### ISSUE THREAD

**Issue by LarkPix** [eclipse/paho.mqtt.c#1297]
https://github.com/eclipse/paho.mqtt.c/blob/7c0735a5f02052c275baddb4f01f1f4dabdfed20/src/Socket.c#L1412

Socket_setWriteContinueCallback() called only in MQTTAsync.c,when the socket was used in sync model, and the network outage and recovery,it meets a seg fault

**Comment by LarkPix** [comment]
`static void MQTTClient_writeContinue(SOCKET socket)`
`{`
	ListElement* found = NULL;

	FUNC_ENTRY;

	/* find the client using this socket */
	if ((found = ListFindItem(handles, &socket, clientSockCompare)) != NULL)
	{
		MQTTClients* m = (MQTTClients*)(found->content);

		m->c->net.lastSent = MQTTTime_now();
	}
	FUNC_EXIT;`
`}`

`Socket_setWriteContinueCallback(MQTTClient_writeContinue);`

this fix the problem, but if it's OK in the code?

**Comment by LarkPix** [comment]
`static void MQTTClient_writeContinue(SOCKET socket)
{
	ListElement* found = NULL;

	FUNC_ENTRY;

	/* find the client using this socket */
	if ((found = ListFindItem(handles, &socket, clientSockCompare)) != NULL)
	{
		MQTTClients* m = (MQTTClients*)(found->content);

		m->c->net.lastSent = MQTTTime_now();
	}
	FUNC_EXIT;
}

Socket_setWriteContinueCallback(MQTTClient_writeContinue);
`
this fix the problem, but if it's OK in the code?

**Comment by tonyjansan** [comment]
I met the same issue.

![image](https://user-images.githubusercontent.com/8926698/203996953-686df781-a0b4-40a9-906e-9e11b5077943.png)

**To Reproduce**
1. Start MQTT broker
2. 'ifconfig eth0 down' about 6~10 sec   or   turn off 4G/Wi-Fi network
3. 'ifconfig eth0 up'   or   recover 4G/Wi-Fi network

**Expected behavior**
Do not crash any more.

**Environment**
OS: Linux and Windows
Version 1.3.11

**Comment by icraggs** [comment]
Tracking under #1286
