### ISSUE TITLE
Connection lost exception

### ISSUE THREAD

**Issue by laszlogyimothy** [eclipse/paho.mqtt.c#1311]
I just tested the new release: 1.3.12 and I have faced an issue:

MQTT_Client, connection_lost callback: 

I do here a reconnect ( I call the MQTTClient_connect5() then I call MQTTClient_subscribeMany5() and return... ) => exception here:

https://github.com/eclipse/paho.mqtt.c/blob/f7799da95e347bbc930b201b52a1173ebbad45a7/src/MQTTClient.c#L714

Based on the documentation, it is allowed to do a reconnect in the connection lost callback and with the previous versions it worked as well. https://eclipse.github.io/paho.mqtt.c/MQTTClient/html/callbacks.html

I just did a comparison between the latest and the previous versions and this timeout here is new. Probably my action takes more than the timeout, 5000 here: 

https://github.com/eclipse/paho.mqtt.c/blob/f7799da95e347bbc930b201b52a1173ebbad45a7/src/MQTTClient.c#L1961

Can you please check this issue?

**Comment by icraggs** [comment]
You shouldn't call subscribe in the connection lost callback, if that's what you're doing, only connect. If you want to retain subscriptions you can use clean session = false, or in MQTT 5.0 have a sufficiently large session expiry interval.

Is that what you're doing?

What sort of exception are you getting (presumably because the semaphore has been destroyed)?

**Comment by laszlogyimothy** [comment]
Thank you very much!

Yes, this is what I am doing.

And I got an exception because of the destroyed semaphore.

(Note: maybe you should update the documentation because of this semaphore
timeout. If the user blocks the connection lost callback longer than the
timeout, then he will get an exception. And this is new in this version,
this timeout.)

Ian Craggs ***@***.***> ezt írta (időpont: 2023. jan. 5., Cs,
15:11):

**Comment by laszlogyimothy** [comment]
I just read the documentation again [https://eclipse.github.io/paho.mqtt.c/MQTTClient/html/_m_q_t_t_client_8h.html#a41108d4cccb67a9d6884ebae52211c46] and it says:

MQTTClient_connectionLost: ..." It is called by the client library if the client loses its connection to the server. The client application must take appropriate action, such as trying to reconnect or reporting the problem."...

There is nothing about any timeout. 

Is this timeout really necessary? I think, this timeout could cause a compatibility issue as well. E.g.: reporting the problem takes long time -> old version works, new version throws an exception.

**Comment by icraggs** [comment]
The timeout was introduced to fix another issue, calling destroy before the connection lost callback had completed. So the disconnect waits for the connectionLost callback to finish, which seems reasonable. 

Why would reporting the problem take a long time? It seems that this problem only arises because a long time is being taken in the connection lost callback (which is not what was intended). 

I should make the disconnect call obey the timeout limit anyway. It was submitted as a PR and I hadn't noticed that.

**Comment by laszlogyimothy** [comment]
I am sorry for the late answer!

I see. It seems, I have to reduce the time of reporting the problem or do
it in a separate thread.

Ian Craggs ***@***.***> ezt írta (időpont: 2023. febr. 14.,
K, 1:00):
