### ISSUE TITLE
WSS connection issue ( WebSocket HTTP rc 404)

### ISSUE THREAD

**Issue by kramis-1** [eclipse/paho.mqtt.c#1314]
For host urls say 
wss://abc.com:1884 

a topic/path (/mqtt) is auto appending to the Websocket upgrade request. 
This is seen in the file 
WebSocket.c 
 -WebSocket_conncet(networkHandles *,int, const char*)
  -- if (!topic)
       topic = "/mqtt"; (Changing this topic to "/" will work)

Appending this topic as a default option will return  WebSocket HTTP rc 404 error and thereby fail the connect request.
Proposal to provide option to set a topic or path option via an API

**Comment by icraggs** [comment]
It will only fail presumably if the broker you are connecting to does not like the /mqtt topic? What is that broker? 

You can connect to:

wss://abc.com:1884/

and it will work?

**Comment by icraggs** [comment]
@fpagliughi what do you think about the websocket /mqtt topic default?

**Comment by kramis-1** [comment]
> 

Yes the broker i connect to doesn't like the mqtt topic.
And yes ,when I connected to wss://abc.com:1884 this worked. I was able to fix this by changing the default topic from /mqtt to / in (Websocket.c).

When the topic path isn't explicitly mentioned why should the default /mqtt be appended. 

Query : Also is it mandatory for a broker to support the /mqtt topic ?

**Comment by icraggs** [comment]
I think you can remove the default topic by adding the final /   ??

Both MQTT 3.1.1 and 5.0 specs say:

_If MQTT is transported over a WebSocket RFC6455 connection, the following conditions apply:
...
· The Client MUST include “mqtt” in the list of WebSocket Sub Protocols it offers [MQTT-6.0.0-3].
· The WebSocket Subprotocol name selected and returned by the Server MUST be “mqtt” [MQTT-6.0.0-4].
· The WebSocket URI used to connect the Client and Server has no impact on the MQTT protocol._

I think that's why we set mqtt as the default. I certainly think that the broker shouldn't consider the mqtt topic to be an error.

**Comment by icraggs** [comment]
Reading my last comment back, I think that the mqtt topic shouldn't be an error. You didn't say what broker it was, but I think it should support this. I'm going to close this issue now, if there's any further discussion you can reopen.
