### ISSUE TITLE
Do we support WASI?

### ISSUE THREAD

**Issue by oceanlvr** [eclipse/paho.mqtt.c#1331]
Is the WASI implemented and if it can be retrofitted to the WASM, how do I do it?

**Comment by icraggs** [comment]
I don't really know what the question means. I looked up WASI and this was the first hit: https://github.com/WebAssembly/WASI, which says:

_The WebAssembly System Interface is not a monolithic standard system interface, but is instead a modular collection of standardized APIs. None of the APIs are required to be implemented to have a compliant runtime. Instead, host environments can choose which APIs make sense for their use cases._

Would you like to explain what you had in mind? I always imagined the C library being part of a lower powered or embedded environment.

**Comment by fpagliughi** [comment]
This has come up a few times for the Rust client since Rust had good, early WASM support.

WASM is a portable binary format for a virtual machine, initially targeting web clients and servers. I believe the intent was to allow the use of different and more efficient languages than JavaScript in the browser. But now it is expanding as a more general purpose virtual machine, so there is interest in using it for different communications and IoT applications.

Unfortunately, though, to my knowledge, WASM doesn't currently support threads which are an essential part of this library. That alone would make it impossible to port in it's current form.

**Comment by oceanlvr** [comment]
> I don't really know what the question means. I looked up WASI and this was the first hit: https://github.com/WebAssembly/WASI, which says:
> 
> _The WebAssembly System Interface is not a monolithic standard system interface, but is instead a modular collection of standardized APIs. None of the APIs are required to be implemented to have a compliant runtime. Instead, host environments can choose which APIs make sense for their use cases._
> 
> Would you like to explain what you had in mind? I always imagined the C library being part of a lower powered or embedded environment.

I apologize for the unclear problem description. May I ask if it is possible to port paho.mqtt.c to the browser environment? Thank you.

**Comment by oceanlvr** [comment]
> This has come up a few times for the Rust client since Rust had good, early WASM support.
> 
> WASM is a portable binary format for a virtual machine, initially targeting web clients and servers. I believe the intent was to allow the use of different and more efficient languages than JavaScript in the browser. But now it is expanding as a more general purpose virtual machine, so there is interest in using it for different communications and IoT applications.
> 
> Unfortunately, though, to my knowledge, WASM doesn't currently support threads which are an essential part of this library. That alone would make it impossible to port in it's current form.

Thank you for your response. I understand.

**Comment by oceanlvr** [comment]
related issue:
https://github.com/eclipse/paho.mqtt.rust/issues/157

**Comment by icraggs** [comment]
Thanks @fpagliughi 

So we can close this as not possible right now?

**Comment by oceanlvr** [comment]
Yes. Thank you. 🙏  icraggs.
