### ISSUE TITLE
Debug Assertion Failed! with HIGH_PERFORMANCE=1

### ISSUE THREAD

**Issue by mbutaru** [eclipse/paho.mqtt.c#1361]
**Describe the bug**

A perfectly working project switched to being compiled with HIGH_PERFORMANCE=1 leads to runtime assert/crash.

**To Reproduce**
1. Build paho mqtt c with HIGH_PERFORMANCE=1 or with the rest of the defines written below.
2. Run any application that uses the build from 1.

**Expected behavior**
To not runtime assert/crash.

**Screenshots**
![Screenshot 2023-05-19 174036](https://github.com/eclipse/paho.mqtt.c/assets/17544061/709fa351-d3cf-49da-8e69-0616a62faae2)
![Screenshot 2023-05-19 174211](https://github.com/eclipse/paho.mqtt.c/assets/17544061/43a95d0b-f7d1-4c43-a101-874a72be2514)

** Environment (please complete the following information):**

Run environment: Windows 10 22H2, Visual Studio 2019 16.11.20
Run configuration: Debug x64
Preprocessor Definitions: WIN64;_WINDOWS;_DEBUG;_LIB;WIN32_LEAN_AND_MEAN;PAHO_MQTT_STATIC=1;HIGH_PERFORMANCE=1;OPENSSL;
Paho version: 1.3.12

**Additional context**

**Comment by icraggs** [comment]
That's not quite the case, because builds with that flag are run on every change as part of the CI tests: https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/history

It could be something in your application, in which case a client library trace as outlined in the readme might help, or a description of what it is doing.

There are some fixes in the develop branch too, you could try that to see if it makes any difference.

**Comment by icraggs** [comment]
No further info.
