### ISSUE TITLE
build with -DPAHO_BUILD_SAMPLES="TRUE" and -DPAHO_WITH_SSL="FALSE" fails to build

### ISSUE THREAD

**Issue by MocioF** [eclipse/paho.mqtt.c#1387]
**Describe the bug**
Testing the gentoo ebuild, a build bug was reported: https://bugs.gentoo.org/912262
The ebuild fails when gentoo's use flags are set to -ssl and +example.
Those use flags, pass 
-DPAHO_BUILD_SAMPLES="TRUE"
-DPAHO_WITH_SSL="FALSE"
 to configure.

The problem does not appears when building on system where libpaho-mqtt-c was previously installed, but only on systems where the library was not in path, so it seems that samples links to the system library (not checked).

**Expected behavior**
samples should build with -DPAHO_WITH_SSL="FALSE" or -DPAHO_BUILD_SAMPLES="TRUE"  should "depend" on -DPAHO_WITH_SSL="TRUE"
However, samples should not rely on preinstalled library files.
*
 - OS: LInux 
 - Version 6.1.41-gentoo

**Comment by icraggs** [comment]
I don't think the not building on systems where libpaho is not already installed is the case, because the CI builds would fail when the samples are built on Github and AppVeyor where samples are built.

Samples needing SSL/TLS I can see would be true - not many builds are run without TLS these days.

**Comment by icraggs** [comment]
I've disallowed the CMake build if those options are selected - that is, SSL must be selected if the samples are to be built.
